print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                          WELCOME TO THE KITTIKHUN GAS STATION              ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::                                                                            ::')
print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

y = 1
while True :
	if y == 1 :
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                               Oil price today                              ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                        1.Gasoline 95 price 29.19 Baht                      ::')
		print('::                                                                            ::')                      
		print('::                        2.Gasoline 91 price 25.30 Baht                      ::')
		print('::                                                                            ::')                         
		print('::                        3.Gasohol  91 price 21.68 Baht                      ::')
		print('::                                                                            ::')                        
		print('::                        4.Gasohol E20 price 20.20 Baht                      ::')
		print('::                                                                            ::')                        
		print('::                        5.Gasohol  95 price 21.20 Baht                      ::')
		print('::                                                                            ::')                         
		print('::                        6.Diesel      price 21.10 Baht                      ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
   
	   
		f = input ("Which type of fuel do you want to choose?  :   \n Want to choose  =>>> :   ")   
       


				                                                                  
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                     Choose a method of kicking money                       ::')
		print('::                                                                            ::')
		print('::                        1.Price reduced in liters                           ::')
		print('::                                                                            ::')
		print('::                        2.The number of liters is the price.                ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::                                                                            ::')
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')


		e = input("Which one do you want to choose? : \n Want to choose   =>>>  : ")



		if "1" in e:
		    n1 = input (" Amount to be entered     \n Money entered  =>>> :   ")
		    g1 = int( n1 )

		elif "2" in e :
		    n2 = input (" Required number of liters     \n Number of liters put  =>>> :   ")
		    g2 = int ( n2 ) 

		if "1"  in e:
		    if '1'   in f  :
		        u = ( g1 / 29.16 )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '2'   in f :
		        u = ( g1 / 25.30  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '3'   in f :
		        u = ( g1 / 21.68  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '4'   in f :
		        u = ( g1 / 20.2  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '5'   in f :
		        u = ( g1 / 21.2  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '6'   in f :
		        u = ( g1 / 21.1  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::',      'Amount of fuel received =>>:'  , '%.2f' %u , 'liters'  ,          '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    else :
		        print("The information is incorrect, please check again")


		elif "2" in e :

		    if '1'  in f  :
		        u = ( g2 * 29.16 )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '2'   in f :
		        u = ( g2 * 25.30  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        
		    elif '3'   in f :
		        u = ( g2 * 21.68  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '4'   in f :
		        u = ( g2 * 20.2  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '5'   in f :
		        u = ( g2 * 21.2  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    elif '6'   in f :
		        u = ( g2 * 21.1  )
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::'                 "Total amount :  ",'%.2f' %u , "Baht " ,                 '::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::                                                                            ::')
		        print('::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::')

		    else :
		        print("The information is incorrect, please check again")
                
		    x = int(input("Chose 1 for to work  Chose 0 for Stop working\n"))
		    y = x
	elif y == 0:
		print(" Stop working ")
		break

